### ISSUE TITLE
Meet java.lang.CloneNotSupportedException in TestDistributedLogConfiguration

### ISSUE THREAD

**Issue by jiazhai** [apache/distributedlog#200]
**BUG REPORT**

- What did you do?
CI tests failed in PR #199 

- What did you expect to see?
all test pass

- What did you see instead?
```
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.645 sec - in org.apache.distributedlog.TestBKSyncLogReader
Running org.apache.distributedlog.TestDistributedLogConfiguration
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.327 sec <<< FAILURE! - in org.apache.distributedlog.TestDistributedLogConfiguration
loadStreamConfNullOverrides(org.apache.distributedlog.TestDistributedLogConfiguration)  Time elapsed: 0.01 sec  <<< ERROR!
org.apache.commons.configuration.ConfigurationRuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.distributedlog.TestDistributedLogConfiguration.loadStreamConfNullOverrides(TestDistributedLogConfiguration.java:87)
Caused by: java.lang.reflect.InvocationTargetException
	at org.apache.distributedlog.TestDistributedLogConfiguration.loadStreamConfNullOverrides(TestDistributedLogConfiguration.java:87)
Caused by: org.apache.commons.configuration.ConfigurationRuntimeException: java.lang.CloneNotSupportedException: org.apache.commons.configuration.MapConfiguration$1 does not implement Cloneable
	at org.apache.distributedlog.TestDistributedLogConfiguration.loadStreamConfNullOverrides(TestDistributedLogConfiguration.java:87)
Caused by: java.lang.CloneNotSupportedException: org.apache.commons.configuration.MapConfiguration$1 does not implement Cloneable
	at org.apache.distributedlog.TestDistributedLogConfiguration.loadStreamConfNullOverrides(TestDistributedLogConfiguration.java:87)

```

**Comment by sijie** [comment]
@jiazhai I think #199 already fixed this issue. closed this as 'won't fix'
